stages:
    load_data:
        cmd: python src/load_data.py --config=params.yaml
        deps:
        - src/get_data.py
        - src/load_data.py
        - data_given/winequality.csv
        outs:
        - data/raw/winequality.csv
    split_data:
        cmd: python src/split_data.py --config=params.yaml
        deps:
        - src/split_data.py
        - data/raw/winequality.csv
        outs:
        - data/processed/train_winequality.csv
        - data/processed/test_winequality.csv
    train_eval: 
        cmd: python src/train_and_evaluation.py --config=params.yaml
        deps:
        - src/train_and_evaluation.py
        - data/processed/train_winequality.csv
        - data/processed/test_winequality.csv
        metrics:
        - reports/params.json:
            cache: false
        - reports/scores.json:
            cache: false
        params:
        - estimators.ElasticNet.params.alpha
        - estimators.ElasticNet.params.l1_ratio
        outs:
        - saved_models/model.joblib
        
